object_detection_node:
  ros__parameters:
    standalone: true
    minimum_prob: 0.4 # minimum confidence probability for a detection to be accepted

    # topic names
    image_raw_topic : "/camera/image_raw" #raw image frames from the drone's camera
    all_detected_topic : "/camera/all_detected" # image frames in which all persons (and specified objects) are detected
    bounding_boxes_topic : "/all_bounding_boxes" # list of person bounding boxes
    tracking_info_topic : "/tracking_info" # topic to publish the information on persons and objects for llm-base commands package

associator_node:
  ros__parameters:
    standalone: true


